// Configuración de la API de Gemini
// REEMPLAZAR "TU_API_KEY_AQUI" CON TU CLAVE REAL
// NUNCA SUBAS ESTE ARCHIVO A GITHUB CON TU CLAVE REAL.
export const GEMINI_API_KEY = "AIzaSyBNuPZb2rSl10yJUTY8Hp5aF0rpb7DE8BY";
